Больше деталей
htmlacademy-javascript/1521379-keksobooking-22 pull request #5
Opened 2021-02-10 18:28 UTC by kusyash

2021-02-12 02:52 UTC, bzvyagintsev commented
Все комментарии и console.log из кода надо убрать

2021-02-12 03:28 UTC, bzvyagintsev requested changes

2021-02-12 03:28 UTC, bzvyagintsev commented on js/main.js
> +  let items = [
Все `title` и `description` надо тоже вынести в константы и генерировать случайные данные на лету.

2021-02-12 03:28 UTC, bzvyagintsev commented on js/main.js
> +    }
А бывают ли кейсы, когда author и location !== undefined? Это же генерация данных, на этом этапе они всегда undefined.

2021-02-12 03:28 UTC, bzvyagintsev commented on js/main.js
> +const randomArray = function (array, count = 0) {
Эту задачу можно решить так: перемешать массив и взять первые count элементов. Получится случайный набор элементов.

2021-02-12 03:28 UTC, bzvyagintsev commented on js/main.js
> +const shuffleArray = function(array) {
Эта функция изменяет входной массив. Это потенциально может вызвать ошибки.

2021-02-13 17:35 UTC, kusyash commented on js/main.js
> +    items[i].offer.price = randomInteger(100, 5000);
Исправила на rooms и guests

2021-02-14 22:49 UTC, bzvyagintsev requested changes

2021-02-14 22:49 UTC, bzvyagintsev commented on js/main.js
> +const getRandomArray = function (array, count = 0) {
Можно просто так:

```
fn(array, count = 0) {
  const mix = shuffleArray(array);
  return mix.slice(0, count);
}
```

2021-02-14 22:49 UTC, bzvyagintsev commented on js/main.js
> +const generateOffer = function () {
```
fn() {
  const item = {
    author: {
      avatar: `...`,
    },
    offer: {
      title: ...,
      ...,
    },
    ...,
  };

  return item;
}
```

2021-02-14 22:49 UTC, bzvyagintsev commented on js/main.js
> +  let items = [];
По идеи, можно const, тк переменная не переопределяется

2021-02-14 22:49 UTC, bzvyagintsev commented on js/main.js
> +  item.offer.address = getRandomFloat(35.65, 35.7, 5).toString() + ', ' + getRandomFloat(139.7, 139.8, 5).toString();
Можно тоже применить шаблонную строку

2021-03-03 16:00 UTC, merged